### ISSUE TITLE
[Bug] Old mod files are not getting deleted

### ISSUE THREAD

**Issue by FolfyBlue** [HughBone/fabrilous-updater#6] opened 2021-08-28 07:45 UTC
Hey, upon using the auto delete feature, mod files are not getting deleted, and upon game launch the launch will halt with the duplicate mods error. I believe this is due to the fact that Windows does not allow you to delete files that are currently in use.

**Comment by HughBone** [comment] 2021-12-18 05:15
Duplicate of Issue #4

**Closed by HughBone** 2021-12-18 05:15 UTC
